version: '3.3'
services:
  snake:
    image: 'dchirwa/snakegame-website:latest'
    container_name: snake_app2
    environment:
      - PORT=3000
    ports:
      - "80:3000"
    volumes:
      - ./:/app
    restart: always
